micronaut:
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:guestUi/browser
        mapping: /**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      assets:
        paths: file:/asset/
        mapping: /asset/**
  application:
    name: PosBuddy-core
  security:
    x509:
      enabled: true
    intercept-url-map:
      -
        pattern: /**
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /assets/**
        http-method: GET
        access:
          - isAnonymous()
  ssl:
    enabled: true
  server:
    ssl:
      client-authentication: want
      key-store:
        path: classpath:ssl/keystore.p12
        password: posBuddy
        type: PKCS12
      trust-store:
        path: classpath:ssl/truststore.jks
        password: posBuddy
        type: JKS
      port: 443
    dualProtocol: true
    port: 80

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/posbuddy
    username: posbuddy
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
